services:
  timescale:
    image: timescale/timescaledb:latest-pg17
    container_name: kymarium-timescale
    environment:
      POSTGRES_DB: ${DB_NAME:-kymarium}
      POSTGRES_USER: ${DB_USER:-kymarium}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-kymarium-this-is-a-really-long-password}
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: kymarium-dragonfly
    command: ["--default_lua_flags=allow-undeclared-keys"]
    environment:
      - DFLY_requirepass=${REDIS_PASSWORD:-kymarium-dragonfly-password}
    ports:
      - "6379:6379"
    volumes:
      - dragonfly_data:/data

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: kymarium-backend
    depends_on:
      - timescale
      - dragonfly
    ports:
      - "8000:8000"

  website:
    build:
      context: ..
      dockerfile: docker/Dockerfile.web
    container_name: kymarium-website
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  timescale_data:
  dragonfly_data:
